name: Config Ignore Keys
type: module
description: Allows the developer to ignore particular keys in the configuration
core: 8.x
core_version_requirement: 8.x || ^9
package: Config
dependencies:
  - drupal:language
