services:

  config_ignore_keys.config_import_event_subscriber:
    class: Drupal\config_ignore_keys\EventSubscriber\ConfigImportEventSubscriber
    arguments: ['@state', '@config.factory', '@config_ignore_keys.plugin.manager.config_ignore', '@language_manager', '@language.config_factory_override']
    tags:
      - { name: 'event_subscriber' }

  config_ignore_keys.plugin.manager.config_ignore:
    class: Drupal\config_ignore_keys\Plugin\Manager\ConfigurationIgnorePluginManager
    parent: default_plugin_manager
